version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: ip-postgres-db
    environment:
      POSTGRES_USER: tamanna
      POSTGRES_PASSWORD: password
      POSTGRES_DB: internship_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ip-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ip-express-backend
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      DATABASE_URL: postgresql://tamanna:password@db:5432/internship_platform?schema=public
      JWT_SECRET: my_super_secret_key
      JWT_EXPIRES_IN: 7d
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - ip-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ip-nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - ip-network
    restart: always

volumes:
  pgdata:

networks:
  ip-network:
    driver: bridge
