version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: ip-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - ip-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: ip-mysql-analytics
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: placement_analytics
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - ip-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ip-express-backend
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      NODE_ENV: production
      JWT_SECRET: my_super_secret_key
      JWT_EXPIRES_IN: 7d
      MONGODB_URI: mongodb://mongo:27017/internship_platform
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: placement_analytics
      MYSQL_PORT: 3306
    depends_on:
      - mongo
      - mysql
    networks:
      - ip-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ip-nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:5001/api/v1
    depends_on:
      - backend
    networks:
      - ip-network
    restart: always

volumes:
  mongodata:
  mysqldata:

networks:
  ip-network:
    driver: bridge
